config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: %i[index show]
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    # respond_to do |format|
    #   format.html
    #   format.js   # show.js.erb
    #   format.turbo_stream
    #   format.json { render json: @product }
    # end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dynamic Pages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container p-5 m-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/index.html.erb
<h1>Список товаров</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="card mb-3">
        <div class="card-body">
          <h5><%= product.name %></h5>
          <button class="btn btn-primary btn-details" data-id="<%= product.id %>">Details (AJAX)</button>
          <button class="btn btn-secondary btn-fetch" data-id="<%= product.id %>">Details (Fetch)</button>
          <%= link_to "Details (Turbo)", product_path(product), data: { turbo_frame: "product_info" }, class: "btn btn-success" %>
          <button class="btn btn-warning btn-stimulus" data-id="<%= product.id %>">Details (Stimulus)</button>
          <button class="btn btn-warning"
                  data-controller="product"
                  data-product-url-value="/products/<%= product.id %>.json"
                  data-action="click->product#show">
            Details (Stimulus)
          </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2>Product Info</h2>
<!-- <div id="current_product_info"></div> -->
<turbo-frame id="product_info"></turbo-frame>
<div id="some-id">

</div>

app/views/products/partials/_product_details.html.erb
<h3><%= product.name %></h3>
<p><%= product.description %></p>
<p><strong><%= number_to_currency(product.price, unit: "₽") %></strong></p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/products/show.js.erb
$("#some-id").html("<%= j render partial: 'products/partials/product_details', locals: { product: @product } %>");

app/views/products/show.turbo_stream.erb
<%= turbo_stream.replace "product_info" do %>
  <%= render partial: "products/partials/product_details", locals: { product: @product } %>
<% end %>